apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: postgres-cluster-store
  namespace: cnpg-pods
spec:
  configuration:
    destinationPath: s3://cnpg-backups/
    endpointURL: http://rustfs-svc.rustfs.svc.cluster.local:9000
    
    s3Credentials:
      accessKeyId:
        name: rustfs-credentials
        key: RUSTFS_ACCESS_KEY
      secretAccessKey:
        name: rustfs-credentials
        key: RUSTFS_SECRET_KEY
    
    wal:
      compression: gzip
      maxParallel: 2
    
    data:
      compression: gzip
      jobs: 2
    
  retentionPolicy: "5d"