apiVersion: v1
kind: Secret
metadata:
    name: rustfs-credentials
    namespace: cnpg-pods
type: Opaque
stringData:
    RUSTFS_ACCESS_KEY: ENC[AES256_GCM,data:ulMSegs=,iv:izHsq116h/h7gGxF8WBvCsfa9zuhMU4PwavEypsg4/c=,tag:PtqHv+YM2/zWGl63J1rTWA==,type:str]
    RUSTFS_SECRET_KEY: ENC[AES256_GCM,data:zR08FOUzG3k=,iv:BW2BdyIGe5mulRu40niZz9j7gDM1otgnaklVUFaRDhw=,tag:OzKPYviEp6tUezEDU6wtow==,type:str]
sops:
    age:
        - recipient: age10ksdmv2awqtaawdcykp7xqpk03t0w2dam92jyzqa945cpmk3t46s7z5xmd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBveGYrMkdmS2dBNmtWcUY2
            YW5VVkRVZklva0dRME5Vd1Y3SDk4L2IwM1RrClZsL1NEV1hhR1FlRUdmdGhPK0l6
            SnAxT0pBd051eDZtT09XSjlYbHFEUzAKLS0tIGc4bEdUZ0Era1RVc0dRT1ZEc3VX
            cFpzRXZsK09DcWdrQ0NaQTFRa1FkZXMKHbtjsc2jaOsE1t33XB980y+IvJ13LdfJ
            IR2CfbcwGTcpDm0ProVANei4fQN2pkEZ0WGy5XEt+BXF23EoawigaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T07:52:23Z"
    mac: ENC[AES256_GCM,data:5KmI/Ss5sLVJyNivlwd4CnSQBv+U0VfMrN0DvVbddDRpXfCtvcmNcWkgPU3CimzpYFh0XLd7snoAE3r0BBHLUVg+2Z0mgDpSmF55bjYnKfPuY1mLUfzct1kViw1QB7+VGK6FGX89mkyGMFBe9NVkhD0ev9du8WukBa1WDG0KsSU=,iv:D1aMOLc0dSrlZ47J6xt5MlBlkGx8zUxMu2P8r/j9MIA=,tag:DbwhgQl92xF5XgKRKGPwZA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
