apiVersion: v1
kind: Secret
metadata:
    name: airflow-metadata-db-connection
    namespace: airflow
type: Opaque
stringData:
    connection: ENC[AES256_GCM,data:Sjg93g9nTYOkpDIFBg+Mz5j8IGVzJLwp0UHpICTpSJlJ8yx0ChykPH9yKTf79AgmT9BlHxeVG772CgRcQU5YXesIwix2u+4FlgpLdS+l7nvkD9R4qr3mRUk=,iv:G7TJFiOf97LidpFB9L4eUTwuB1jtsdEC7SG0N+8Q0EI=,tag:NNmNfDBGkrD5bpQJ4F82dg==,type:str]
sops:
    age:
        - recipient: age10ksdmv2awqtaawdcykp7xqpk03t0w2dam92jyzqa945cpmk3t46s7z5xmd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDUmZuS3hsOWt4cmdTMFhD
            MzB2MGJ3YzlJWU9DRWdFR2R1dmhYbzc0K3cwCk0vLzgrM1hKQjN6amxDOGxKREp2
            WGViblFqa0gySGFmK2t4WmdZdHB0dGMKLS0tIFNrc2xFYnR1ajBtSmZ4M2JCK2d3
            S0YyazY2ZVlEdDBCQ0ZURDJXd1hsSHcKgqzkLGl7aTrHRTlUr/7NZouQnYbapDYn
            qUlxFDPCesrOihCfMbVa99c2j/MxnMWVP9Soe8+qw2wR72iruqKAkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-02T19:24:58Z"
    mac: ENC[AES256_GCM,data:7UnPQU+rNnbInHqqs2O6omJUTAszWnN1M/h9Ex8l2O+gcTJVsmbQH8jYP343q/Wki+lwlGdLe97WNG+zlQgy3tXI05fLWuEXqqtDe3YojVWsQeW3bl1aouTclFmVe79Imaj3V1BJcaCZfaeaccAtz7eBIa/4fO77VBxv+x7+PZg=,iv:DXbS5g8U/EJ6GxrePDFmnTPti0mt9VFhoJUcXmLUBl4=,tag:5aogRFAdHV8vY0plLet7Qw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
