apiVersion: v1
kind: Secret
metadata:
    name: cnpg-superuser
    namespace: airflow
data:
    password: ENC[AES256_GCM,data:ome2Uz4ptnD+VO3UG1A4iSQroBIgFk11AvZAcas3tmZ+oc4x1fPrSiS10KWLNFeTpS5mNiSdLtpejDIe/GDJovCkB0r3dkEsJcOStiMi2kJoVmGV1pr6og==,iv:Y9FcEtWtZykSwvFdPcBvGv5hu89316sdAQJSJjCi984=,tag:JeZRviGrReDOvM3o20vdhg==,type:str]
    username: ENC[AES256_GCM,data:GzhSOeN++0P8HlAV,iv:/qGAmPxPqUyawGrmybJ+rShMRkxe99RVsMgim/FdF68=,tag:pyytCxdUQj9adbm4CUnPyQ==,type:str]
sops:
    age:
        - recipient: age10ksdmv2awqtaawdcykp7xqpk03t0w2dam92jyzqa945cpmk3t46s7z5xmd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCbFpPNTVGN2NpWkJtU0hH
            WEc5RGtKR3Z0bEgvQlE4OVVzeHliUWREaUY4Ck5vbzhIUDIzOWFuSEpDM0lKWFFx
            N2kzakJrUjNpSHFJdWN1TEtCSmIxY3MKLS0tIEN5UXRVQTBNbmJLb21keU5WY1dq
            QnVFcXBXaXNJWTVYNCtOWHN4bDVXNkEK6vtoJxUmT8/U75tF5dmQ5gvWfUBbdhxu
            qX0hKYtQ5WGSw3bDey+hZTFYjhojLRg6SarTtj4oaaIDnCoMILS+2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-02T22:47:38Z"
    mac: ENC[AES256_GCM,data:EHGZ3O59wYO+A7Pc+hqTk9RaFd1JxeNjD7rD5ZgMXIcfOcdkEZSa7mG1htg1lY8MxntQcN3khkV+912c8r+Fdm3uAxdQOykDJmbIpUEuVIqV7Jl++i05oT5xoBRXpj0BWMwLvDH6jzZ13ViDEUJKyluySXytgCt52eeyDVZCo9E=,iv:KNoTH0IWv6DjNvg2S0VPRmJhePqU1Hfz7T+cWlNDH38=,tag:aRlTK4cCKN3Vpwosk6JpLA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
