apiVersion: v1
kind: Secret
metadata:
    name: airflow-db-credentials
    namespace: airflow
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:t9TBYlSE0A==,iv:/RXOjMi/by37tFLzXbBampfdZopQor/KZsuhogQf0Rw=,tag:BwNLG9qbim5EG0s8J4U3pw==,type:str]
    password: ENC[AES256_GCM,data:Tq8LOc+QVw==,iv:Z+Tetlq65aE9XTNmbnrHuBHTAUZfys+AUgVASmfyG8Y=,tag:WnDmscd2LxFwMGh5bbXWjA==,type:str]
    database: ENC[AES256_GCM,data:zhGNeojrQw==,iv:YXw2i+zGtlAZCZN2duA3709Q5YUaRhn1wsC08yII84o=,tag:7PEhJedkHyQeeDIjWoQDSw==,type:str]
sops:
    age:
        - recipient: age10ksdmv2awqtaawdcykp7xqpk03t0w2dam92jyzqa945cpmk3t46s7z5xmd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZ2NtbWM4UU5FUzVZU0kx
            TmtNSnVxYUNWN2FncWhnOW9iWmdnZ2d4eGl3CkRCMkVkNEZhSXdOMFdMbzV0Zmgv
            djJReEdkVzdKZHhxV0plU0NRd01xMWsKLS0tIGxUZXA1YW8zd0RWdXBQaUFodEIw
            Kzlqck5CaXpTMjZUTmpZTGEvVE1OajQK8NtIJwmuOgRfoX4FW2zDVNQl+WV7/9Cg
            zSqnr9cbUhXPRXG3lWvLdcb0mO6AOstol6jsXaDcGUnGb4gIbcCQQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-02T22:37:38Z"
    mac: ENC[AES256_GCM,data:uZnUhYKpXV3pyM2zBoSUucx//4CqGrDcJi+iPrpX2lRGDoPb1Q4t9v3D0x2edeybdqXZAMzC9JyqlhNGmNES1cQQoYkMB/JF/DK5BgfF2zC0pzrIzdjQQplw3i3jlqEdEILKTBjheQRjcwiaNoPWGSavGgr2Ux1Ea7RCdApc+JY=,iv:iadY+ucMyU16jT2kIaDwE8XndtnJ2DfoVOkiyZ6cmIo=,tag:2F77rJLcXcNfGXaJslNxtw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
