apiVersion: v1
kind: Secret
metadata:
    name: airflow-minio-connection
    namespace: airflow
type: Opaque
stringData:
    AIRFLOW_CONN_MINIO: ENC[AES256_GCM,data:EAwn/5tEtm9ggXAnbPFiPMw8Dwm+n4mnJDM5xt7f8E8n7QiCX3ZfEGVIeyT71O6T5Ubt3SmsioPxxOIETOjhe+Xdm8eXI4sAaN5q+XWKwVxHQsaSNIGVwPmrN8gq2iGv3uqbfuOP9JgocFzgqnkShd+HAkuwGjTxSj+SNeSujubPa74zTi+K0W3sHyTaNs6zes4oArM80M4McV0ugqj6if4S5q1sT3at8w==,iv:x3+DkeMtYYsv9Z/k/grn7Tm0NklCEDHIrexfLslMsk4=,tag:jFeqa3ykglOOvhHDlfg4wg==,type:str]
sops:
    age:
        - recipient: age10ksdmv2awqtaawdcykp7xqpk03t0w2dam92jyzqa945cpmk3t46s7z5xmd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmTnNsR24xcmhmbzUyajhI
            anBXSlI3NXh5SUk4N2F6QS82dVJYa0VteHc0CnJ6cEwrUkE1N010ZUxBdkY0VjVh
            R0NEUThJR1B3TW5PSHJNRjdpYk4xbTAKLS0tIGVIdklyczVidy9jS2o1UFZyaFVF
            VWp3cEVsWGlUSkN4U2dKQlVTRklLaG8Krl5PkbhL9ApfMmxW38CZAEFjxk4QIl3D
            edlvA6AjB/1oe4shCJ/V6cHdPmSwL0k6ptn3WopB3KwSzPkbFrQAkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-02T19:24:49Z"
    mac: ENC[AES256_GCM,data:8/saehfvhQJhr3+StuqJEgM2O7j08YFqeO1ygkE70zd4NbzUBh99g0Kz9nKzobyBFX1cVkz7a6XMi0FKh/eu/PbIZ69D5W78qGH3tyN7ghRTnUdlZ1gqlMOUhwAALPjmETyHwcv0IdRwfsqlqnRglPOtdLAyswUX3BXorlVpj4o=,iv:TyoiTQKv1RxrklIDe0EhKtfKrWh/Vz2Zl0Ap2AH20yU=,tag:WJq6JscyVnueBjc6HCwJKw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
