apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-ip
  namespace: redis
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  selector:
    app: redis