apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: cnpg-pods
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:15.4
  storage:
    size: 10Gi
    storageClass: longhorn-single-replica

  superuserSecret:
    name: pg-superuser-secret
  
  managed:
    services:
      additional:
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: "cnpg-rw-lb"
            spec:
              ports:
                - name: postgresql
                  port: 5432
                  targetPort: 5432
              type: ClusterIP

  bootstrap:
    initdb:
      database: appdb
      owner: appuser
      secret:
        name: pg-app-secret