apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - pgvector.yaml
  - read-superuser-secret-role.yaml
  - multi-namespace-superuser-secret-rolebinding.yaml
  - read-cluster-clusterrole.yaml
  - multi-namespace-cluster-read-clusterrolebinding.yaml