apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-postgres-superuser-secret
  namespace: cnpg-pods
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["postgres-cluster-superuser"]
    verbs: ["get"]