registry_mirrors:
  docker.io:
    upstream: "https://registry-1.docker.io"
    harbor_project: "dockerhub"
  ghcr.io:
    upstream: "https://ghcr.io"
    harbor_project: "ghcr"
  quay.io:
    upstream: "https://quay.io"
    harbor_project: "quay"
  registry.k8s.io:
    upstream: "https://registry.k8s.io"
    harbor_project: "k8s-registry"
harbor_hostname: 10.10.10.50
harbor_scheme: http