{{- if .Values.minio.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.minio.app | default "minio" }}-headless
  namespace: {{ .Values.minio.namespace | default "minio" }}
  labels:
    app: {{ .Values.minio.app | default "minio" }}
spec:
  clusterIP: None
  selector:
    app: {{ .Values.minio.app | default "minio" }}
  ports:
    - port: 9000
      name: api
    - port: 9001
      name: console
{{- end }}