{{- if and .Values.minio.enabled .Values.minio.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.minio.app }}-ingress
  namespace: {{ .Values.minio.namespace }}
spec:
  ingressClassName: {{ .Values.minio.ingress.className }}
  rules:
    - host: {{ .Values.minio.ingress.apiHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.minio.app }}-loadbalancer
                port:
                  number: 9000
    - host: {{ .Values.minio.ingress.consoleHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.minio.app }}-loadbalancer
                port:
                  number: 9001
{{- end }}