apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
  namespace: monitoring
spec:
  interval: 30m
  timeout: 15m
  
  install:
    remediation:
      retries: 3
  
  upgrade:
    remediation:
      retries: 3
  
  chart:
    spec:
      chart: alloy
      version: '0.x'
      sourceRef:
        kind: HelmRepository
        name: grafana-alloy
        namespace: monitoring
      interval: 12h
  
  # Wait for Loki to be ready
  dependsOn:
    - name: loki
      namespace: monitoring
  
  values:
    # Deploy as DaemonSet (one pod per node for log collection)
    alloy:
      
      configMap:
        create: true
        content: |
          // Grafana Alloy Configuration
          
          /********************************************
           * Logging Pipeline
           ********************************************/
          
          // Discover all pods on this node
          discovery.kubernetes "pods" {
            role = "pod"
            namespaces {
              names = []  // Empty = all namespaces
            }
          }
          
          // Relabel to extract pod metadata
          discovery.relabel "pod_logs" {
            targets = discovery.kubernetes.pods.targets
            
            // Keep only pods on this node
            rule {
              source_labels = ["__meta_kubernetes_pod_node_name"]
              regex         = env("HOSTNAME")
              action        = "keep"
            }
            
            // Add namespace label
            rule {
              source_labels = ["__meta_kubernetes_namespace"]
              target_label  = "namespace"
            }
            
            // Add pod label
            rule {
              source_labels = ["__meta_kubernetes_pod_name"]
              target_label  = "pod"
            }
            
            // Add container label
            rule {
              source_labels = ["__meta_kubernetes_pod_container_name"]
              target_label  = "container"
            }
            
            // Set log file path
            rule {
              source_labels = ["__meta_kubernetes_pod_uid", "__meta_kubernetes_pod_container_name"]
              target_label  = "__path__"
              separator     = "/"
              replacement   = "/var/log/pods/*$1/*.log"
            }
          }
          
          // Read logs from files
          loki.source.kubernetes "pods" {
            targets    = discovery.relabel.pod_logs.output
            forward_to = [loki.process.pod_logs.receiver]
          }
          
          // Process logs: parse CRI format, extract trace_id/span_id
          loki.process "pod_logs" {
            // Parse CRI format (timestamp, stream, message)
            stage.cri {}
            
            // Try to parse JSON logs and extract trace context
            stage.json {
              expressions = {
                trace_id = "trace_id",
                span_id  = "span_id",
              }
            }
            
            // Add trace_id and span_id as labels (if they exist)
            stage.labels {
              values = {
                trace_id = "",
                span_id  = "",
              }
            }
            
            forward_to = [loki.write.default.receiver]
          }
          
          // Write logs to Loki
          loki.write "default" {
            endpoint {
              url = "http://loki-gateway.monitoring.svc.cluster.local/loki/api/v1/push"
            }
          }
    
    controller:
      type: "daemonset"
    
    # Resources for each Alloy pod
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
    
    # ServiceMonitor for Prometheus to scrape Alloy metrics
    serviceMonitor:
      enabled: true
      labels:
        release: kube-prometheus-stack
    
    # Mount /var/log/pods for log collection
    extraVolumes:
      - name: varlog
        hostPath:
          path: /var/log
    
    extraVolumeMounts:
      - name: varlog
        mountPath: /var/log
        readOnly: true
    
    # Security context
    securityContext:
      privileged: false
      runAsUser: 0  # Need root to read /var/log
      runAsGroup: 0