apiVersion: v1
kind: Secret
metadata:
    name: jupyterhub-hub-secret
    namespace: jupyterhub
stringData:
    proxy.secretToken: ENC[AES256_GCM,data:UwQXOyW+KoNo8kYNJZNqIJcy7abyuAhpj5MgeVwF+zLBa0QAnzZ5/fKABhhaH+y/Jdch6OLYlAutXSydk18eMw==,iv:M2A3qYRsOlKoeuqoOXCkOxmjmxAqiBBq9rxZMOQqveA=,tag:8DgzbBJSJq2FlO/PYDKfRg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrNFJJY25HWGQyQXNEanJJ
            cnR2dG9FbkJZTWpQNTRIUjRYTUFTZnIwTHkwCkFKcU1UeDdwdVA3UTF2bHlMM1d1
            akQxdVRiN1BKWXV4ejU3SU84U0xJYzAKLS0tIFpGTFZWNnJZUWgrNll3WVJtYUg1
            VUF0Tk15QUlESmEzSDJJbndVbFN1K0UK1nMEh5cv2POUuBIZfDSVYPbxOsvQt6f4
            3tPayf8pKMbd2v0e88eDrfsSYWYjaw1gFYx7Omx26WCt7VOGy1hhfA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ksdmv2awqtaawdcykp7xqpk03t0w2dam92jyzqa945cpmk3t46s7z5xmd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-09T18:18:17Z"
    mac: ENC[AES256_GCM,data:BO9Jx2QpwDytR/K3AVRsM2yD4K2rzUTRILZenLm5khoo0CegPw9grfRCquFthCegPwkJG5QTTTvfBylcKcb/QjHiII7dcJeIicSN9DKuXAAlKsahB6PEKK8OqndRjoqwIlYxRDv0KSjA94SqQYMGquQLW7wzGn8lJwaLO1ylNzU=,iv:YezVZTWe7gf1dYLnfdbnvq2Y+c5KIHtVgkqo1SF7o8s=,tag:hj2mJ6HrRmFGau6RWyFaNg==,type:str]
    version: 3.13.2
