apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- httproute.yaml
- httpsroute.yaml
- rustfs-credentials-secret.yaml
- jupyterhub-spark-serviceaccount.yaml
- helmrepository.yaml
- helmrelease.yaml