apiVersion: v1
kind: Secret
metadata:
    name: rustfs-credentials
    namespace: jupyterhub
type: Opaque
stringData:
    RUSTFS_ACCESS_KEY: ENC[AES256_GCM,data:WV+vZ0M=,iv:h7pPSiegOSbgeWoRCHh4pOxDwSXc/f1OWZfgGCOXrbE=,tag:dMlACxvKDrYIlBIlRt8VQA==,type:str]
    RUSTFS_SECRET_KEY: ENC[AES256_GCM,data:KpfVqNX2mkA=,iv:AKOvxB0Tf/HMky5ip2RlpTtdqhw1Aljma0pdRwws838=,tag:vUEAaqQsxmbpPvL31hFf4Q==,type:str]
    ENDPOINT: ENC[AES256_GCM,data:lsjIXT/QnMeJuNvwNElJhzop0mRcvsH9ZKfQ4L0Llu7iGwnoqVVEOxEQ3Nr87hQ=,iv:llxbRB2rAjzUjf8jqTN3dI92lgiDgsm0+vpuw3Fl1OI=,tag:d6VS3K38MX7YkPkMfnRUaw==,type:str]
sops:
    age:
        - recipient: age10ksdmv2awqtaawdcykp7xqpk03t0w2dam92jyzqa945cpmk3t46s7z5xmd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3T0FzOS9xY3NaYjl6YlhS
            d2JseC9idUF4SGFhU3A2ZHZaRS9SV1JiTkNrCndNQU9kbTZrTGxEaE0yTFZpZkZ5
            S0RMREE1K3g4K2svSHdsVTJWeGlJSDQKLS0tIHM0RUlpR0ZjcElrbXVQNUgzSHp2
            ZkFDVzdpTDB3YTQ0bjhoc2ZTZWROemcKSeshNmOY5HOqJE1NJs+RnbTV3FiNf1sO
            giv0oGLrX/+pvCNhiE/ZTXiF/QqPbJHpqqr+1unAZNTtr5wToIqGsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T23:09:43Z"
    mac: ENC[AES256_GCM,data:A4yGcdFY/L01EKbmFNIgli9pNEyCBfTS5We9G1oAhGTfpgGPaETafXsJ/LuX6beML8LBBfnSPKnNJVEd7HmWkbFP+zbeZsgJemgH7phOQiNNoRfAiviM2v/L4cU7meWkG+l6dxRxw5mck/gAdW6z+YQtd9Cm0mVKlfgZ1AwQ3k0=,iv:VeEFzG4phtR3ysrff3U1K0kM6Dovdf07S5W7RNAlYyE=,tag:CnmGKaChq3rQ8PiVMU/QdQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
