apiVersion: v1
kind: Secret
metadata:
    name: rustfs-credentials
    namespace: jupyterhub
type: Opaque
stringData:
    RUSTFS_ACCESS_KEY: ENC[AES256_GCM,data:P0sfAGs=,iv:GoyAjrVMDKq2bUUkJATg9IcXUUck8Pkjm4LrgQIpWio=,tag:fFo86Y1TcRYbs90X47o+ig==,type:str]
    RUSTFS_SECRET_KEY: ENC[AES256_GCM,data:EuGqlW3JQTk=,iv:OBpkquK6aE05w7jXQ674I4WbG/mNYopV922ObE2Fgnc=,tag:aJzC1jRpTwBl5iDYL5kQLA==,type:str]
    ENDPOINT: ENC[AES256_GCM,data:ARuy8ifPBYfWCSF81CX3NFAazVN0yDlHeaZK8TaRx8tStWo4FuaERFv/qdX8iEXNQVP1zg==,iv:91JcbLQTl+sAvzF0vyPv0F31d9iRz59piY3nTLrVuoM=,tag:UyfH3lQAus79jDe0XnacLQ==,type:str]
sops:
    age:
        - recipient: age10ksdmv2awqtaawdcykp7xqpk03t0w2dam92jyzqa945cpmk3t46s7z5xmd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZZHVxUC9hdXd5WTlTNmdG
            MURHeEgzbEN0UnRtZTJZWGVUcjJ4WEJHV0JFCi9MbXhHQUJoRVhpNFc5UmRMbDFY
            cUozTlRjRjBhRy9aTklBVDd1V2pvSkkKLS0tIHJKRWdDbE1ibHE4RG0wbDNENWlv
            K2JlZDN6U3l3TXFZNmpCWW5MZHUzQ0UKQlKBO2taCm8/zNds0VLSE10ib3aIfjvC
            2R5tachCBhuIcnHuTu9JUtEnUMwY3wUfkIKVoYrffYq3vx6e/psHWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T07:51:53Z"
    mac: ENC[AES256_GCM,data:LtAt8FZHLixkqotkgsh3YaIFFyvFdbzvD1VrkHRcqj96TU3OnJgZ+JRqNWql5NLQhtz6Nuo9ELHutXs+4JZCNguqpDCsFIOEgCOk1j64j74MOKmUSVpzBnE6ZpqGP3bWnKza+CffWdCjLeNs5s01LIY3bqVKasuFJqrweerC8uU=,iv:G9XkPhZ7gL24zKAwI4Ndv9KSM687d9UhpL0FWcqlwmI=,tag:8y+DISiW31haJmucjmBdqQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
