apiVersion: v1
kind: Service
metadata:
  name: minio-backend-loadbalancer
  namespace: minio
  labels:
    app: minio
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.10.10.121
spec:
  selector:
    app: minio
  ports:
    - name: api
      port: 9000
      targetPort: 9000  # Maps to MinIO API
  type: LoadBalancer