{{- if .Values.cloudnativepg.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cloudnativepg.superuser.secretName }}
  namespace: {{ .Values.cloudnativepg.namespace }}
type: Opaque
stringData:
  username: {{ .Values.cloudnativepg.superuser.name }}
  password: {{ .Values.cloudnativepg.superuser.password }}
{{- end }}