{{- if .Values.cloudnativepg.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cloudnativepg.superuser.secretName | default "pg-superuser-secret" }}
  namespace: {{ .Values.cloudnativepg.namespace | default "cnpg-pods" }}
type: Opaque
stringData:
  username: {{ .Values.cloudnativepg.superuser.name | default "postgres" }}
  password: {{ .Values.cloudnativepg.superuser.password | default "postgresuserpassword" }}
{{- end }}