{{- if .Values.cloudnativepg.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cloudnativepg.appuser.secretName | default "pg-app-secret"}}
  namespace: {{ .Values.cloudnativepg.namespace | default "cnpg-pods" }}
type: Opaque
stringData:
  username: {{ .Values.cloudnativepg.appuser.name | default "appuser" }}
  password: {{ .Values.cloudnativepg.appuser.password | default "appuserpassword" }}
{{- end }}
