{{- if .Values.cloudnativepg.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cloudnativepg.appuser.secretName }}
  namespace: {{ .Values.cloudnativepg.namespace }}
type: Opaque
stringData:
  username: {{ .Values.cloudnativepg.appuser.name }}
  password: {{ .Values.cloudnativepg.appuser.password }}
{{- end }}
