{{- if .Values.cloudnativepg.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.cloudnativepg.clusterName | default "postgres-cluster" }}
  namespace: {{ .Values.cloudnativepg.namespace | default "cnpg-pods" }}
spec:
  instances: {{ .Values.cloudnativepg.instances | default 3 }}
  imageName: {{ .Values.cloudnativepg.image.repository | default "ghcr.io/cloudnative-pg/postgresql" }}:{{ .Values.cloudnativepg.image.tag | default "15.4" }}
  storage:
    size: {{ .Values.cloudnativepg.storage.size | default "10Gi" }}
    storageClass: {{ .Values.cloudnativepg.storage.storageClass | default "standard" }}

  superuserSecret:
    name: {{ .Values.cloudnativepg.superuser.secretName | default "pg-superuser-secret" }}

  bootstrap:
    initdb:
      database: {{ .Values.cloudnativepg.appuser.appdb | default "appdb" }}
      owner: {{ .Values.cloudnativepg.appuser.name | default "appuser" }}
      secret:
        name: {{ .Values.cloudnativepg.appuser.secretName | default "pg-app-secret" }}

  # affinity:
  #   nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #       - matchExpressions:
  #         - key: db-role
  #           operator: In
  #           values:
  #           - postgres
{{- end }}