{{- if .Values.cloudnativepg.vector.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: {{ .Values.cloudnativepg.clusterName | default "postgres-cluster" }}
  namespace: {{ .Values.cloudnativepg.namespace | default "cnpg-pods" }}
spec:
  name: {{ .Values.cloudnativepg.appuser.appdb | default "appdb" }}
  owner: {{ .Values.cloudnativepg.appuser.name | default "appuser" }}
  cluster:
    name: {{ .Values.cloudnativepg.clusterName | default "postgres-cluster" }}
  extensions:
    - name: vector
{{- end}}
