apiVersion: v1
kind: Service
metadata:
  name: portfolio-frontend-loadbalancer
  namespace: portfolio
spec:
  selector:
    app: portfolio-frontend
  ports:
  - name: http
    port: 80
    targetPort: 5000
    protocol: TCP
  type: ClusterIP