apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- httproute.yaml
- httpsroute.yaml
- rustfs-connection-secret.yaml
- metadata-db-airflow-credentials-secret.yaml
- metadata-db-init-job-serviceaccount.yaml
- metadata-db-init-job.yaml
- metadata-db-secret.yaml
- create-rustfs-log-bucket.yaml
- rustfs-credentials-secret.yaml
- helmrepository.yaml
- helmrelease.yaml