apiVersion: v1
kind: Secret
metadata:
    name: airflow-rustfs-connection
    namespace: airflow
type: Opaque
stringData:
    AIRFLOW_CONN_RUSTFS: ENC[AES256_GCM,data:YI3DkO95yT2x3w5sGNv8lfA8aAmnXkBxets654KZg0oAzLYgtqfMSNXeoAvp209kiCekM+Djqpey5cFWQZOnpNryK645VOH64GKcegdYg1UWL1wboiRHdcfv1vcf4D7Q5KuT2Vc5F8MDP51TjuHpxXXyC6aDdlszgTSRUdeY0Wq4HD8hNsr6IDYlxa93TAO4Hons3KhauV4ozq7jecb3WoVpj3Z/ln+W+HNRZgiaC+yg0PCSbXDQIbvqHQie1AJxslQpzv5TPUnoZtxe45sRRjxnXPjiARSDM7OVLUv9Gpt7jXtq8FAy8icRMN94DZfV2/gjbyeE0vodM0eKsReFvP7UyjlCpb+f6Z2JVyzbShKbD+em3Q==,iv:Ls7IW0SsD1Mi7LraJ9NzQaCTbyvJtWTAgjwZrNRQA2k=,tag:lKRaCgsfCEey4/Wp334sHA==,type:str]
sops:
    age:
        - recipient: age10ksdmv2awqtaawdcykp7xqpk03t0w2dam92jyzqa945cpmk3t46s7z5xmd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLQkZWbWtFSlFNTExUekVV
            MkphQTk5NnUrWDRhU29QTTN0alJZYy84SnhVCkJmL0NUazFDeXBzZEhrQkZ5WDcy
            YjY2cXkvdGZaS2N2QTJhY0t1aW55VmcKLS0tIG1DR0RJZkx6TEsvaEhQUEY0YkE0
            YnFZNTN3a2E2OEo4Y0lLMVkybXh2UzQKmkwXQBJKH4eCIhFAqZVUbBV9i8q8fNds
            c2LwmxfUUUR8J1XyLPkNpqScXDLF+j1AYUWVBZTcg13MMYq35A/4UQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T23:09:22Z"
    mac: ENC[AES256_GCM,data:dydSdWAXJnntEygVzXr43UoOuUpnoSAbv675QBw2dA0NNbRwHu+SWjPHL1L9jeaRSwQQNmWpGPRjw/jzdH6bg9OzI3vGtvBly1nmc2+24VocXxWROfB70UT2cF6SUlO5puBudVtM6nC26Ol7JtQ0UaIIL2wEMJNAJgWgMCLiBg4=,iv:dHliIzLwkob1YxppB4pFKb70yyowtHu4CXJpr9AgtXE=,tag:SYua6yVGixZJ4at2ZY9t8w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
