apiVersion: v1
kind: Secret
metadata:
    name: airflow-rustfs-connection
    namespace: airflow
type: Opaque
stringData:
    AIRFLOW_CONN_RUSTFS: ENC[AES256_GCM,data:Ewk690UphiZHAcoIR7XG07MIg3FNNLEUz3V3707V5YfnGcRXLxfKjsnHT9s1J7TPq6U4S4qkkE1hve5UR4ldyboqrEPV51IJbl6F9Nx9vvBtmrNgzVMuc+zT4+nFBkW0JOR5yzRvs3u1jEWxJU7m7HYjojvyv55K2UI8ExKySJPhSTQAUlz45n/H3tgs+wrKXyd0l39GUCf8fjz0uo4eP9bCEijNJ94bxe45tPnRGkOs6QPoS8slc6N6a3OrYZVHUR5YzgXrHM+lKTztDbWRO+6ZKcezxk7Mu0l3U3B4oD/iyWGy08At1oY1yOWP3Kd6orI0qvZY7T4lvrcooUkY4gsnTmaGVvzGx5fU2dFr9WkAX4y7xyh2O6Vk,iv:+OzXXqdCV0OhhsRKkK0Kj/PRWN1UkwvJ8TbdukuToy8=,tag:H/ze5tbdFPEkN7fAhvYL7A==,type:str]
sops:
    age:
        - recipient: age10ksdmv2awqtaawdcykp7xqpk03t0w2dam92jyzqa945cpmk3t46s7z5xmd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6SFBjdVFlVThoODJkV3hX
            aU4ySmVOeHVjN2pYSjJuV1F5dG9YaisxZFdrCnEyV056L3AzM25DQjBMTUJUMFJo
            eE42Q3g3VjBMSXJianBKQ2dxbEtIUHMKLS0tIEY3SUV4Q01BYkRsblRKV1BUNlo3
            VHA4SUw5SmI5aGxadFNXQVF1REo0MmcKR5mYe3R2XQCYPPCGwhENA91fOXM1TKTc
            YfLIvg3zCqyKgODIA9QhNFAkzoUBdigtBf9PZMjDDVJP4/WS5JgGRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T07:32:05Z"
    mac: ENC[AES256_GCM,data:qzY9IOx73z9Yey8fxqfOPhasrbTHjdRXRNGu41sKjPwu4Qiv6oWJf3WybhhPMR/F2NlcER5ZqnzA6drGkkTCaDpnQdET5xfYmFo7JRX5y+4m1UGncyOqqHfyXdZGasNuZfB1p13fEczhBAnxewY1GaO8qwD+34cTHACQefqfGq4=,iv:IF3291oWu7euzwqJUo6sbVYExbCAf8si4/ZmaCJH96w=,tag:S69VQ37eCiwOCmXdOYCnoA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
