apiVersion: v1
kind: Secret
metadata:
    name: airflow-minio-connection
    namespace: airflow
type: Opaque
stringData:
    AIRFLOW_CONN_MINIO: ENC[AES256_GCM,data:DlGnAQzounhOAOduZVujWcZHuYRL4i1+Fz8o/hysAmF7+49VX/1tkN0jmc7uiK9nqTlad4XGq8ID1X3Q8fdmZmKpQFo84C4h+yiz6M/TnVE7XnuSs4xuZnlP1bmQkndsTwBKsvxuXrW5FNQDfpu6i9vY4AQwkEMH84K7c43KYxEktu7VTNxoMVCcJszVPQczho/qulIeC0wo+UmYo+X7ngfHKxbMgjOMnZUuVLg1TCAqmuEr0UIAYcEsL4qtUouK5C+1tJCGGCQb8TgmIPhrlgSZiCuguRpjZpxZxoj1sOrRyaMlydNeaXWXzu4yMXg5WzH/ncmlMiljjpM1jedVztkcxgLZEUui0m3DPzGlLng+eifSXSM1c9fX7d3vmCATOFcyhg==,iv:ls2u9sumULH7mnsYvksAeE+K9H5/ofPjwIOzOK7FwHo=,tag:x9H2xdX7AY58sgbNcdhS3A==,type:str]
sops:
    age:
        - recipient: age10ksdmv2awqtaawdcykp7xqpk03t0w2dam92jyzqa945cpmk3t46s7z5xmd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWY0l6SkZFZFFFNUNOYWx5
            d2NaT25GUWFEVjBoNm03WVBUTWc5Szk3VmdnClBJOW04MjZRcmVBQUJhNXZXT3hJ
            dzBXL1lJRTBYOG5ZK1dnWmpDQ1BuN28KLS0tIEVvZE9yTEtXL25TMUJKcjBJTTN0
            Q29xMkwvcm82RG96ODBXL2JoVU5kOWsKA4mf3ydcYDlhc5DAAA6u4tujy0qpT+rk
            ole3tLIlXWutBDAdM+Qhj+Uji8KAkCZlzDD98swGKwLOz1AyS6FhGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-03T05:52:36Z"
    mac: ENC[AES256_GCM,data:TDbrsWVAmcuDGNOx1aMSiU9s5KPj7r/WyAPnFBXw7tKIVLhaKtpr/4akO7AuJdn7F9QN1QLz/VJEotAQbi+GyZvndF8tuAbUIUOtMfCgc88rOQRzL2h9EgMakdLatxHwH79QWyGWEAbukbSVqDDBvJBKbkU+WxRTEYkNCscT19k=,iv:2QjuK+/S9A/NJRMdpc5TgAXcT6OblKznInC7DMgVPbg=,tag:x/j1Wi+mTadEHovlpBA3Cw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
