apiVersion: v1
kind: Secret
metadata:
    name: rustfs-credentials
    namespace: airflow
type: Opaque
stringData:
    RUSTFS_ACCESS_KEY: ENC[AES256_GCM,data:2JtKkrM=,iv:V4osjBAHFXt3VYHa4xmxi9Ar2Esu7vQzbvd2/nlLflc=,tag:pOZrDXVpHnB09NmYkgC+CQ==,type:str]
    RUSTFS_SECRET_KEY: ENC[AES256_GCM,data:kdcuN2l2NwM=,iv:FsNFYwfXRmoDxoxoXsRCrAf4RnSiRCd608BsFtFmuXE=,tag:xoBjCmlm7TwTAgiH2BEQew==,type:str]
sops:
    age:
        - recipient: age10ksdmv2awqtaawdcykp7xqpk03t0w2dam92jyzqa945cpmk3t46s7z5xmd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0aUlMa0Q3TVEwS1VMZ0Yv
            SHNVdUNRZURQWmhHMjZ0OHZIVUFmK2xRQXdBCmpqMmhOTWtjUHNtaThJNTRhdGU2
            WUVaRmpRR0pNS2tvbWpqdmZGOEhhQ2sKLS0tIGE3c2hwc3h4S2tYTEh1OVhnYWNl
            cUdqcWM0UU1HSllGcHVlbG1HbDkxblkKz8EPp+8xLuXCOFXnCMVTWkN3h9Fzjuuw
            ZxVBG2RP2GI3y5V8MA3r+t3DBooc0BGw2y+b6Bl3xg29q+grfi5UNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T07:51:13Z"
    mac: ENC[AES256_GCM,data:F0XG2PqozxfswiQBARctS1ncpWKb4gOZfCP98xu1M4v/rlJD5UYnL3CYaa1RvGTsNi1NaBYSXY84ome4IgmvzWZ7tu3655kyiC0Gxq01L+MH6JqR11qN9id9EYD3TGt83ViybFo4E4flAxZvOZfZdN/mRTAh86quc5fN+tT6tJ4=,iv:wGOY8CYzVALZFKCcTJcEkElWrKGeojKFn2Q2T8Mfl88=,tag:rkCEqkb1SMMLCWRb4KQk4w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
