registry_mirrors:
  docker.io:
    upstream: "https://registry-1.docker.io"
    harbor_project: "dockerhub"
  ghcr.io:
    upstream: "https://ghcr.io"
    harbor_project: "ghcr"
  quay.io:
    upstream: "https://quay.io"
    harbor_project: "quay"
  registry.k8s.io:
    upstream: "https://registry.k8s.io"
    harbor_project: "k8s-registry"
harbor_hostname: cacher.home.com
harbor_scheme: https
apt_cacher_ng_hostname: 192.168.1.162
apt_cacher_ng_port: 3142
dns_server_ip: 192.168.1.201
kubeconfig_out: "{{ lookup('env','HOME') }}/.kube/config-production"