apiVersion: v1
kind: Secret
metadata:
    name: minio-credentials
    namespace: jupyterhub
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:EViniYg=,iv:avzcfurmPbWv9X8cz+66eN4dYAqYuFOS4aFn7cx8u4g=,tag:Ti2WB3g580ULMQfWRJnpGg==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:bGwDxb9Nivk=,iv:93v/xAETYlBWTEL8OO4jKyQtBejPS3ahIPggoI57z/c=,tag:6gisMrdpAhziIEli0Drexw==,type:str]
    ENDPOINT: ENC[AES256_GCM,data:SUKLXWCHSl1350Q90uvcPH8hcyKRJyofcMWov3D2oTHATKtjTEY2MHqfRYi8Ota8ahHAbg7Sm9DJc0IMskc=,iv:6MmCrb1phIYH6HdWF0MOgsNywSc6v2RZWMXaDLvOmNo=,tag:ccE+fBIoSV9hggeqjhxIgg==,type:str]
sops:
    age:
        - recipient: age10ksdmv2awqtaawdcykp7xqpk03t0w2dam92jyzqa945cpmk3t46s7z5xmd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsRlQzTEcrd0p2Vmk4WTdE
            cUg2cDBROHEzTUhQa2xQQ2R0SzZoMUNvREVFCmN6T2prRDVubVl6YUtLWldQQ2FO
            VnF6LytqdklmdjExVEZsYlFVSXJhMzQKLS0tIDNvZHdGU3pKNjZPSFE4KzcyaWpP
            N1hqbnVtTFBjVGF6aEFadDBMVnJraEkKdf9L+x4m7OR4Y4qUjaaQI77rbT/bUt+6
            zlKh6MKZygsk++FxibzjGIRkHhcOmKYDJy5HSrL2ojR+P1rZ3Dr3Tw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T20:37:39Z"
    mac: ENC[AES256_GCM,data:yA11iIU2J6OyvDpzqjvhi8XDLSV5G0EOXdkqd7oKbTE0LGyUmDWKGSuRwxVsFFPaoHaubej0uQs/Ygp9X77kwjjkhT8TtdWo1Bt6kT9mqis0oKTJUFyRQLjz/Ujk1DYuS82MKgwgaPWIg/5wdhnofKEJYHKfp/cW7gBA8BRcZuE=,iv:aryQJzIK3ZzWcB/KYbYozIkAuClvvMGy1PKNQmD1sb0=,tag:A8nZ7vNfzzGdlnCCgzvTdQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
