apiVersion: v1
kind: Secret
metadata:
    name: rustfs-credentials
    namespace: rustfs
type: Opaque
stringData:
    RUSTFS_ACCESS_KEY: ENC[AES256_GCM,data:MqTh30k=,iv:WBO3YJfPWhYLbSlq/Xl3ik+ndjI24jWBvqbfnJ3eNow=,tag:rdy8QR/v0x0R3M6I/jBRyQ==,type:str]
    RUSTFS_SECRET_KEY: ENC[AES256_GCM,data:2qZg1jAY/EI=,iv:ENUbkyBMAqn3KVuhvYC0jVIwkna6rzO7UAWr8S3NuAE=,tag:mNI3G4CAugmilFcIM620bA==,type:str]
sops:
    age:
        - recipient: age10ksdmv2awqtaawdcykp7xqpk03t0w2dam92jyzqa945cpmk3t46s7z5xmd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxeko4akFWeXVYcHU2ZVNn
            TEFTTUVoSTdEdSs4M0tPYTdGeGRwUHgweEdFCmhUbk9lVUhLTEs3RE9tT1prc1po
            MlAxL0JyUTBVbWZvbVdMMXVsVy83STgKLS0tIGt5YnJIRTA2WkVlOEhNYlNZSi9y
            d0FKZ0RsK2dtbkUrV2ZUdkdCdFpkMkkKwxXl1iqwdhzix5/yh/Cka6dfaXhqKQnG
            XjseGrTxs5Pikn49EJwMUe96Qm/1YwtztY9Pc1hSRF+1pY+Ise77Jw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T04:16:23Z"
    mac: ENC[AES256_GCM,data:HiToR8TYC7IjTyJPaMLjV17OF70SIVBPfQ+uBYijH1/IwhDiDmmjEWOjFqaVL5KXz44ypZXp49RH6AnvuVRZLFl1r6J/rh0ypBdFMH5TJ1//rfRjOdEYvvh3VAeWl9YcIj7ibME+s5aD67XIHAn+/ZtyZN6+K2MZ4ttGGzKDBvY=,iv:NltI+Gtf9OlYFqdkARS1s8fugP9Pma6jUPqewqAjXNg=,tag:oMNTpMf9bgopTc8r/a6d6w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
