---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-release
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cert-manager-repo
      version: v1.19
  values:
    crds:
      enabled: true
    resources:
      requests:
        cpu: "50m"
        memory: "128Mi"
      limits:
        cpu: "100m"
        memory: "256Mi"
    webhook:
      resources:
        requests:
          cpu: "25m"
          memory: "64Mi"
        limits:
          cpu: "50m"
          memory: "128Mi"
    cainjector:
      resources:
        requests:
          cpu: "25m"
          memory: "64Mi"
        limits:
          cpu: "50m"
          memory: "128Mi"
  interval: 1m0s
  install:
    timeout: 30m
    remediation:
      retries: 3
  upgrade:
    timeout: 30m
