apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-token
  namespace: cloudflare
type: Opaque
stringData:
    TUNNEL_TOKEN: eyJhIjoiOGQ4NjkzYjk2MjI3ZmRlZGFiYzk1NzAyOWJkYzc0YTUiLCJ0IjoiNjJhN2M4N2YtN2I1Ny00YTFiLWI2ZDgtZWY4ODlmYjFiNzRiIiwicyI6Ik9EYzFNbU15WlRFdFpETXdOQzAwTVdaa0xXRmtOemt0TTJSa1l6YzFORFV5TnpJNCJ9