apiVersion: v1
kind: Secret
metadata:
    name: rustfs-credentials
    namespace: redis
type: Opaque
stringData:
    RUSTFS_ACCESS_KEY: ENC[AES256_GCM,data:KZl4CXA=,iv:31J6W1iSMQmykwSrU4ZAQGRbTRFB/J1eSid50ZLxG2Q=,tag:Ne8Jk9MrIyD4QVPdvI3mCA==,type:str]
    RUSTFS_SECRET_KEY: ENC[AES256_GCM,data:/g648N5EJwU=,iv:+ixcVu7wh5J4gBIA+10ynq8tJ8KejY1KEZrVaucyL/Y=,tag:YxMJxUk0jIV5Nzheo7jK4w==,type:str]
sops:
    age:
        - recipient: age10ksdmv2awqtaawdcykp7xqpk03t0w2dam92jyzqa945cpmk3t46s7z5xmd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqbGdyV2hSNHBRUGlUUlhV
            cmVhVnl0cklNalBUNDdyUUlPdFJOemw2UmtJCjMzSFdRckZWMzNjcUFyODl4R2tK
            aTlOYWhWdkIyV0ZUTkUyeWZaaHFtaE0KLS0tIFVpT0hJa1FUVE1KNFAyK0ZUeHVX
            WFVncVhPUnF3dDdpVm1hdnhiL1BOQXcK+qlr39mi7jejEoZjziUGEF7Ar/wO+Qik
            GTBfQdhkSLQtqmSGN05b6Q7hvicZMM7ORLT+Qpw+8XlykLKNy50nVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T07:52:51Z"
    mac: ENC[AES256_GCM,data:SAy6fZzet/i4gr8821rWg86kCJsGsroDmyBQvidVNsSP5cJRg0f6zwQmamsjDv2CtjrTTVB7WP+aB442+/W9x7e7UhswpVEx9sMaoOy8VkL521tR3j+d9Z6y9p2HEeevB/8hjQUAiEJUgD/Q1EUW/0c+CJyCRCHLeXPcUSGb87k=,iv:CPnuePuPK9qpv41RewpGKOiyF8aJk1RkLCXxaWqcWvo=,tag:QNI9suMqlDagu4VnwOtDew==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
