apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: cnpg-pods
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:15.4
  storage:
    size: 10Gi
    storageClass: local-path

  superuserSecret:
    name: pg-superuser-secret

  bootstrap:
    initdb:
      database: appdb
      owner: appuser
      secret:
        name: pg-app-secret

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: db-role
            operator: In
            values:
            - postgres
