apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: crds-success
  namespace: flux-system
spec:
  eventMetadata:
    summary: "✅ CRDs Creation Successful"
    layer: "crds"
  providerRef:
    name: slack-deployments
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: crds
      namespace: flux-system
  inclusionList:
    - "configured$"
    - "created$"
    - "deleted$"
    - "Health check passed"