{{ if .Values.metallb.enabled }}
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: {{ .Values.metallb.l2advert.name | default "advert" }}
  namespace: {{ .Values.metallb.namespace | default "metallb-system" }}
{{- end }}