apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: flux-system
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:lMA5Hg7bAkxw6l3J7Lzi3I4VqOhzIsPxK3Ok4vXnls1eyH1BSSp9RQ==,iv:MJEzsvTo1Mv+fZhOHnsqHXYRYLpSyWuU5XE/5OVmuiE=,tag:cqsZLW9phGklwHDoA3RZDw==,type:str]
sops:
    age:
        - recipient: age10ksdmv2awqtaawdcykp7xqpk03t0w2dam92jyzqa945cpmk3t46s7z5xmd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNc1NoV1Y5RUdiTzlieG5T
            V0VYaEI5bjFKQWQ3cVpIM21WOUg2NUlQTGpNCnVXc3FNUzloUXhVTS9Cd1E1UzlH
            enpwNW05WWp0bUxDUTZhZzV2RWtNMjgKLS0tIGV5VjZIK1Y3dC9yY011eEk0TmFq
            NmZkeGdaQzVOZTZOdVVrenFwaitKSk0KKhqwOpEs6+AIj84GFhWxxakHL/Rje5SQ
            WkbgLtegO3yK0+ebjIrlGa3blfrAHL9GugTGu0KEFLDa8JEsHT39Jw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-01T01:47:18Z"
    mac: ENC[AES256_GCM,data:HVcoL4LQIrlJEDYyU8g4ECL1CYElqAHbfs/GizH6A58J9zdXfP0lwmDP7DPK4a5epb1thacZ62yLa1/oeTn4TIHXS82EGxJMaZ84gUDEByFWh9OloNYeH9QSeBM/nb2EQp+4a73xr3sGb3Ted5meOxc9rkwTOxa6tYCLCTouB1s=,iv:wB0oi6t6+uwG5FwECPXDMUM0xhKmWg84aG5o76lBHs8=,tag:a0WhtSMmY2qYFH3fHhT8vw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
