# helmrepository.yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jupyterhub
  namespace: jupyterhub
spec:
  interval: 24h
  url: https://hub.jupyter.org/helm-chart/