apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 30m
  timeout: 15m

  install:
    remediation:
      retries: 3

  upgrade:
    remediation:
      retries: 3

  chart:
    spec:
      chart: loki
      version: "6.x"             # pin to a specific 6.x when you’re happy
      sourceRef:
        kind: HelmRepository
        name: grafana-loki
        namespace: monitoring
      interval: 12h

  dependsOn:
    - name: kube-prometheus-stack
      namespace: monitoring

  values:
    deploymentMode: SingleBinary

    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1

      storage:
        type: filesystem

      resources:
        requests:
          cpu: "200m"
          memory: "512Mi"
        limits:
          cpu: "1000m"
          memory: "1Gi"

      schemaConfig:
        configs:
          - from: "2024-01-01"
            store: tsdb
            object_store: filesystem
            schema: v13
            index:
              prefix: index_
              period: 24h

      limits_config:
        retention_period: 72h
        max_query_length: 72h
        ingestion_rate_mb: 10
        ingestion_burst_size_mb: 20

    singleBinary:
      replicas: 1
      persistence:
        enabled: true
        storageClass: longhorn-single-replica
        size: 10Gi
      resources:
        requests:
          cpu: 200m
          memory: 256Mi
        limits:
          cpu: 1000m
          memory: 1Gi

    # Disable other deployment modes
    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0

    chunksCache:
      enabled: false
    
    resultsCache:
      enabled: false

    promtail:
      enabled: false

    grafana:
      enabled: false

    gateway:
      enabled: true
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi

    monitoring:
      selfMonitoring:
        enabled: false
      serviceMonitor:
        enabled: true
        labels:
          release: kube-prometheus-stack

    test:
      enabled: false