apiVersion: v1
kind: Secret
metadata:
    name: portfolio-db-credentials
    namespace: portfolio
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:3BLV4+8ynNOH,iv:+cnoN9IbJWcZc3CTSadSqu2p+FrbqI699pNGuAsAdUQ=,tag:EYsJFvjQTfkHDAAEHQe9Qg==,type:str]
    password: ENC[AES256_GCM,data:ao+672FC9iskK0cfw00=,iv:hLQAY+2tg7k66dEMYmJKqqOmzbwPTTbPdHb5m0A03xs=,tag:1iyE825AVrcxTcs4333Ojw==,type:str]
    database: ENC[AES256_GCM,data:fmwsSlxPdd5B,iv:EzbTOCIYaIfya4PD4EB/Qf7SJWSjANwmjMRHNzCCbZc=,tag:iaNb547DSQLGOaHut1T5hQ==,type:str]
sops:
    age:
        - recipient: age10ksdmv2awqtaawdcykp7xqpk03t0w2dam92jyzqa945cpmk3t46s7z5xmd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3aUJuWEU3ZkdKRWZFY045
            eXFwOEpnSVN2RXBaTnBQb2NyUUdxeW9RZURvCjFoWXZUcEowV0ZPd0QvTE5XY1Yw
            Y0dYa0VMWDdLNHJLRDlOQVZLYlZIaWsKLS0tIGdBeVpZa3FOeXJQWlZKc1RPaUc1
            bnptbzk4dXdQd0RxM0Z0WlhHTXBxa00K88OLhIm4HP4D6LwxGy+1MQjAiyvyX/vV
            MyTZM2IqVcFPsB+1nhmTEf46Jj8ScUl6wjxLzkTGio6s8yD1lWtu+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T18:21:57Z"
    mac: ENC[AES256_GCM,data:VK9+zOFIIszaTidSE7P9hHfJvghUzyvM1MEP1iudOjweR+mb3gAloKC04C4tPBlXCUlJ7m1ZAJygUYjdvB+0LyCfe3/0wYX4U8hiOes2N/9ZLFBJsPJ18/qmeApgNT4sfBdqfLor3bPxvr9FPOk/PN7x4BUl24R3iGORww0oO6A=,iv:XS6BvoG8DAmQ9nBhmQQSiprF7Yfgf4uwNCHvcCNGv3I=,tag:1JlBS9YSfj5X/PR+r1JHTw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
