apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
  namespace: monitoring
spec:
  interval: 30m
  timeout: 15m
  
  install:
    remediation:
      retries: 3
  
  upgrade:
    remediation:
      retries: 3
  
  chart:
    spec:
      chart: tempo
      version: '1.x'
      sourceRef:
        kind: HelmRepository
        name: grafana-tempo
        namespace: monitoring
      interval: 12h
  
  dependsOn:
    - name: kube-prometheus-stack
      namespace: monitoring
  
  values:
    # Number of Tempo instances
    replicas: 1
    
    # Tempo container configuration
    tempo:
      
      # Resources
      resources:
        requests:
          cpu: "200m"
          memory: "256Mi"
        limits:
          cpu: "1000m"
          memory: "1Gi"
      
      # Memory ballast for stability
      memBallastSizeMbs: 64
      
      # Disable multitenancy for homelab
      multitenancyEnabled: false
      
      # Enable metrics generator
      metricsGenerator:
        enabled: true
        remoteWriteUrl: "http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090/api/v1/write"
        # Processor configuration
        processor:
          service_graphs:
            wait: 10s
            max_items: 10000
          span_metrics:
            enable_target_info: true
        # Storage paths
        storage:
          path: "/var/tempo/metrics"
        traces_storage:
          path: "/var/tempo/wal"
      
      # Retention period (3 days to match Loki)
      retention: 72h
      
      # Server configuration
      server:
        http_listen_port: 3200
      
      # Storage configuration
      storage:
        trace:
          backend: local
          local:
            path: /var/tempo/traces
          wal:
            path: /var/tempo/wal
      
      # Receivers - accept traces in multiple formats
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: "0.0.0.0:4317"
            http:
              endpoint: "0.0.0.0:4318"
      
      # Ingester configuration
      ingester:
        max_block_duration: 5m
      
      # Querier configuration
      querier:
        max_concurrent_queries: 20
      
      # Query frontend configuration
      queryFrontend:
        search:
          concurrent_jobs: 1000
      
      # Override settings
      overrides:
        defaults:
          metrics_generator:
            processors:
              - service-graphs
              - span-metrics
    
    # Disable tempo-query (legacy Jaeger UI)
    tempoQuery:
      enabled: false
    
    # Security context
    securityContext:
      runAsUser: 10001
      runAsGroup: 10001
      fsGroup: 10001
      runAsNonRoot: true
    
    # Service configuration
    service:
      type: ClusterIP
    
    # ServiceMonitor for Prometheus
    serviceMonitor:
      enabled: true
      interval: 30s
      additionalLabels:
        release: kube-prometheus-stack
    
    # Persistence - use Longhorn single-replica
    persistence:
      enabled: true
      storageClassName: longhorn-slow-single-replica
      size: 10Gi