apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 30m
  chart:
    spec:
      chart: metallb
      version: 0.14.8
      sourceRef:
        kind: HelmRepository
        name: metallb-repo
        namespace: metallb-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace