apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: cnpg-pods
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:15.4
  storage:
    size: 5Gi
    storageClass: longhorn-fast-single-replica
  
  enableSuperuserAccess: true
  
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: postgres-cluster-store
  
  managed:
    services:
      additional:
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: "cnpg-rw-lb"
              annotations:
                metallb.universe.tf/loadBalancerIPs: 10.10.10.110
            spec:
              ports:
                - name: postgresql
                  port: 5432
                  targetPort: 5432
              type: LoadBalancer
  
  monitoring:
    enablePodMonitor: true

  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "2000m"
      memory: "2Gi"