apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 5m
  path: ./cluster/apps
  prune: true
  wait: true
  timeout: 10m
  dependsOn:
    - name: platform-misc
  sourceRef:
    kind: GitRepository
    name: flux-system
