apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: exec-cnpg-psql
  namespace: cnpg-pods
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
