apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: core-errors
  namespace: flux-system
spec:
  eventMetadata:
    summary: "🚨 Core Operators Failure"
    layer: "core"
    priority: "P0"
  providerRef:
    name: slack-critical
  eventSeverity: error
  eventSources:
    - kind: Kustomization
      name: core
      namespace: flux-system