apiVersion: v1
kind: Secret
metadata:
    name: polaris-db-credentials
    namespace: polaris
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:9Vmxb8ufng==,iv:81e6sGqkrjGf1hh3iLf1QMKRNSSgEJcfR3RKmU/dk5M=,tag:kPu3u7QIjVdDLk/EwFUTKg==,type:str]
    password: ENC[AES256_GCM,data:6tOAkZoCFg==,iv:3RCwn/hZl7OnPi4QI1gwYgbKGFkIbr5aO5mOYbmJjto=,tag:tXeFoKaKWY3jrnFFZIbTRA==,type:str]
    jdbcUrl: ENC[AES256_GCM,data:l3DcALAoQcqKvjwgueW0kchlsehNzaUFa/q6QBbSzfFTqp0SLCgK3/C2ta6tjoLYF122rCBm2k5qCPCszLnmzVOVY2dn,iv:muBIKf5HG+kqKh0i/T8VkurPeYpAFwCCM7rQtcJq914=,tag:CGNxn/ahm6Qilc9UY/Kl1A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRNG9DaXB4emJkSW5sN2la
            ZmdhU1BaZXM4Z1RSdHlNaG9mbWEvelgyNVd3CjVlMmZDWHZUeGVVNlNMcGVjdUF0
            dEFYbkxCRUQzZVcvdUJsNWhPNnFQcDAKLS0tIHBJOGhaUk4rdjZBY3UyUWVUS21h
            USs5bkdoMmZVSGd3Z3dqTjk5Rkk0MEkKPdU6X55DFNXyGOZ13sXzec5YMmCQv49p
            Cd6rc7HQc9Uh3P5Lrs/qbfJ/o6CHdcKjbOhut06U5NKKq7Ma628D4g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ksdmv2awqtaawdcykp7xqpk03t0w2dam92jyzqa945cpmk3t46s7z5xmd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T01:32:57Z"
    mac: ENC[AES256_GCM,data:Ts+GmvCdzSQa1lgqWvoGgETQ//j5yjbJb3SB58P8qJf7NvsAZEksNfJeB4wAcywENYxqH8vf4EbVidDtR6oi8XkLaJ1ALy0M2m/jLtEiFtWE2rFd/mHj8l01FownjKtAkTUn0GyoCJn81OHuXeuquGEweSJtwV9q4tOGGuLOE6U=,iv:A4tTs2QL8JL/z+t362YhVbMVWiNtIXxjpN2EeG6Mvh4=,tag:W/4wQ7hX0qmCJghIWpVk/g==,type:str]
    version: 3.13.3
