apiVersion: v1
kind: Secret
metadata:
    name: polaris-root-credentials
    namespace: polaris
type: Opaque
stringData:
    rootPassword: ENC[AES256_GCM,data:nYS2i5l88w==,iv:cmuwnrBdM3twCXxLuvtDE4z0JHpAkJF8LFGU3BlSezw=,tag:0GS4xqDVR9ufl72zAagbUg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWM1Bpa2VaeXB0TFVKWCts
            a0pQYjN6c3dLOVEwYzFlMWo2VmZLdXE0bXowClpaY0JpNzMxc00wYlo3cCs5U25l
            c3U1bFY3b045M3kzbzBudTlnekpxZlkKLS0tIDU2OFlVNWFXYlk4TTZRTGpYaWRQ
            dTcydVdPUUw5QnRCYlloY3FNdnpqbzAKAjPjy9pLezYFXhRBINeSVCDYOUWONDs9
            5P/3fMyEeaBW157JEwbeJaaPJkBGmTaU5qBVApnMO4jbxzARHnW/ng==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ksdmv2awqtaawdcykp7xqpk03t0w2dam92jyzqa945cpmk3t46s7z5xmd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T03:34:25Z"
    mac: ENC[AES256_GCM,data:Du2daAZxzK20K5eBz47uw4NdJxo5eEP730YaFLqjFCOQ4lXFFuUIDbvPaa0D7JEIdUKXylwV7IDKHzL+gnE/QxN6gHH9XU5HoIzlRdq7ylWWcIe1guK+woftOTV55FwNxK6Zezb5xbWGEMSHtHqUTkSYmLFSI7UWtleCnUJfcV8=,iv:DHkcbmpKKSBtx+dKwH+aHOMRzk6eDLliftjZCTDvs7c=,tag:4oCdr/7ZIeiB8DzHSw5tlQ==,type:str]
    version: 3.13.3
