apiVersion: v1
kind: Secret
metadata:
    name: rustfs-credentials
    namespace: polaris
type: Opaque
stringData:
    RUSTFS_ACCESS_KEY: ENC[AES256_GCM,data:w+3c5xc=,iv:Wy9wvg/spfAZ8J7j+rPpbM4UdtaxhbqQYxuT1hMXMCY=,tag:lDJcLqchQDb8phi+6YhoVQ==,type:str]
    RUSTFS_SECRET_KEY: ENC[AES256_GCM,data:iSTUMYifYrM=,iv:Zzf9ZqZQtM4MK3I4kQQARftT7CbkpsWwCZ5JiudtQEg=,tag:mcsjzmMXj8ekODMqpe8MuQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByRnowSHZQS29FZzVkUUtX
            MGpWZXUvQzFPZEdVV1BaOHI4NEZKNnkzRHhrCk1vTFJyRzdkSUFWK2VIa2QvS1lG
            M3dpVTRxSmdqdDhvYWFsT1hnT1Z0YlUKLS0tIEd3U3A0WnpKQlRuSmllajZwT2tQ
            ZmQ0VkpMTE9QbVRYREZSS1FTTmlyZGsKplqubx4onZU8oVzbUPtzwHW/3gW+V+9a
            /lfIWc1vJO/H3XaOLN92+IcyKwTZrE02irF/u5WbUNa5L5TKVPg73w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10ksdmv2awqtaawdcykp7xqpk03t0w2dam92jyzqa945cpmk3t46s7z5xmd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T01:33:17Z"
    mac: ENC[AES256_GCM,data:L9IKE8m+14CzHXgEkJp6lm9/QQ5V3v9BMwDIPqxIi5scJiMKu9VQlJFKejaPWaYfpnXgQuXZ1xgoKwXmZQDmMPFLtdVGajd1CkxCxleiWS4NZpbmKYUqmyvzyP957nc5HabObQmTK4SfEzxQbZfj2UHMHUe/0IVj4VJDJuG11zA=,iv:VaJ5r5E2xYtnxviZ94r2z8nHiHhyqSTz5w0kDKzKrKE=,tag:co4JTWRyolbWCl6+aaekfQ==,type:str]
    version: 3.13.3
