apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- operator-namespace.yaml
- job-namespace.yaml
- helmrepository.yaml
- helmrelease.yaml
- spark-serviceaccount.yaml
- spark-clusterrole.yaml
- spark-clusterrolebinding.yaml