apiVersion: v1
kind: Secret
metadata:
    name: dockerhub-credentials
    namespace: harbor
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:ar/ah8ut/fI5jCgjtfY=,iv:Cvgn0bxB0zstif2z4y7QTaaDiiB79/LxOrIPYhlRoeA=,tag:NxjiIWSWo6JMdv+OO0p8tQ==,type:str]
    token: ENC[AES256_GCM,data:ksbw0mLhRr2uRwDfMVk11YYXm/5nVWAcO4Vl/8pWKzT4EQ0H,iv:U2rjP64pDbDJjejRwe6xYHhHZble+JfrkAaO9EW+loU=,tag:aQPdui+tt1EwEESIV/VXGQ==,type:str]
sops:
    age:
        - recipient: age10ksdmv2awqtaawdcykp7xqpk03t0w2dam92jyzqa945cpmk3t46s7z5xmd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRbWZ6L2lYa253NW05ZnJ4
            K0Zyem9lNXIwaGx3ZjJhL1ZCaW4rY1BsYXp3CkIwdjlycUhPYnhibFFYTkR1aG5X
            ZHRCbm0vUGNmZExpdXYxek1PM0FKQncKLS0tIGZ2K1FiRXFBQkFuYTFNQ05sN2JV
            b2tlTkdpQndWUXJ1VlEyK0krUVlOTTgK78Dlq3lRGXPGXSM7Tn6vStfAFks5w2kG
            1h9MddmwuUdBENJ8kzWA69fHUBBVWWyLvz1j/2k7YRtxcWDiNWwdeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T04:57:10Z"
    mac: ENC[AES256_GCM,data:PzJ6xx3n/184QwWkqlHkLzeQHjL1JYmWxPi1/pPnK9AdlyPPVTaiiSkLxpm6TMDNXgrh7p+6Vqd42WHXHKjgvkO9Me3Gf8GqcCHl+K/HASSL04JRQcRvTH3B/efFxcfajerqKc24I4OrvCRNBFblVn3n3DIlyHjE3oOfgvf+AIo=,iv:jNvUZuNvg5ZkCYgaJLI9OW6V5ATD1v2KjK2U8m/Uf5U=,tag:hRUq8Ods6tnLpETueCEMUQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
