apiVersion: v1
kind: Secret
metadata:
    name: harbor-db-credentials
    namespace: harbor
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:wLhdTA1G,iv:rLL2CbTyJ3qVoP8Eu9oPEn8HxkYqlmDW/Jq6mw86RnM=,tag:62UhlKLfW0KcXAgJ0L7aqg==,type:str]
    password: ENC[AES256_GCM,data:Bx7doyTx,iv:g+AFR+qkO9HCvpKaid6yv4iF5V+pYcqAYIgQWWJvDhY=,tag:ImXb55fzPrcBkgSQXiZ6Lg==,type:str]
    database: ENC[AES256_GCM,data:2ehXM9lZ,iv:Hb+34x+3tTawJWMbAQ9R8mPD+jskQXLOO4AbQL6fxrY=,tag:WdBtEuZuI3IUWibKDpxQrg==,type:str]
sops:
    age:
        - recipient: age10ksdmv2awqtaawdcykp7xqpk03t0w2dam92jyzqa945cpmk3t46s7z5xmd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ZzdHb1gvMWxIYjYxZTlk
            dDNocnY5ZVVReWloVHZDOGRETG1QRGx0WVVNCnBScVNZWXBtdEhMQXVXeTNYY0FO
            UXYvRDZRUXNES3dibHRSWWFVRjNnT28KLS0tIFhNbjlhWUlpb2dHWEM4Tk83ejZK
            dGphZUp6UzBtbGZlRU4xUS9UMEVhV0UKZcmueSGU/O0qxEzgGzK+VehOAUnSzD3D
            4uidrYLXPhwjkNMHvSgQA1sx5X0bZRvp4vHgOP9dp2GufJEBRutclQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T04:57:30Z"
    mac: ENC[AES256_GCM,data:tkDEkVOMCVamG8dDftqN7vShVihsRMAgRCAxwMHNsLATSDipoYshPobI12w3bNm9pP973lJzSeAiD2qAw9Ca1zRdsjc8GFeKPOAGEl5PWHCmS2+JLEsTbGz87LVbE3JhYq1wVBHALaN9le8ooZlA8ZhrEB33v7zQHceUjxp9isY=,iv:CDqgHn3E7dcnQdcEVOtvwCjGnsL5IIP4r0jHiPF1qXI=,tag:QnFg2NCjV73KceOT5CmQ1A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
