apiVersion: v1
kind: Secret
metadata:
    name: harbor-admin-secret
    namespace: harbor
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:eALBxHjrrRc=,iv:x2o9LHKIUODhoEM7zmVAbkmZ4t97e0bFYp+r8H57GDk=,tag:I173BjjHK49zlvmDGypXDg==,type:str]
sops:
    age:
        - recipient: age10ksdmv2awqtaawdcykp7xqpk03t0w2dam92jyzqa945cpmk3t46s7z5xmd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSUZmUm45T0MrUjRhcGp0
            U3V0Qm1qTFVFVFBOYkRGSXQzMVRjdE1lYldBCjd5QUNERlhUV1diamU4Y25raC9r
            RnhFb0FvTDhxRGRWUXBpa3ZKSmtGUFUKLS0tIEFOSFlLZERnVnkyVGg4bHRYcFR4
            SFhDQjk1VUdPODNodE5wSGtEdnpxUFkKcAtBcaHzwFdIpH3XsLPDjiEEvskf9gpV
            pG1cj9xHh0BMY664EKCIDHlRM7NAu2+MZXb67/mVX1oPuUDOJGbvrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T03:40:52Z"
    mac: ENC[AES256_GCM,data:rD+abZqbTkuydH6OU/nb8THbkBNbwvdgkWPVfc/Bd5a1dv6TfgLNkhKUfmfVdladsL30jzjrBM8myKHzBbtXh+oQiAVar98fPjfoOXSpuV9DijPQactmClL594kXFtuL8XylGYO+UYwkNNRP0E26r+1WrtXerEAvkXGJSITDgFk=,iv:oA3RGRrKaqrVZu0UTpd4eh0wuLhoPKN7yZRAZm2BwK8=,tag:nbKpNeBT074uPWJuK9F+oA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
