apiVersion: v1
kind: Secret
metadata:
    name: harbor-minio-credentials
    namespace: harbor
type: Opaque
stringData:
    REGISTRY_STORAGE_S3_ACCESSKEY: ENC[AES256_GCM,data:+Cg2jgs=,iv:Hvy/3vi8FNZnvotqAzY0xFgMwxGGdSASVENnh3LIhKU=,tag:iEM7GLUV9nmTnOK9mJFgsA==,type:str]
    REGISTRY_STORAGE_S3_SECRETKEY: ENC[AES256_GCM,data:3490BJvFlNk=,iv:htVZzppVDbn3wdBxDcd1XErNe9pUNumEbY+/rU1kNHA=,tag:mBGOhtNLDzLeKtY0A2FIXw==,type:str]
sops:
    age:
        - recipient: age10ksdmv2awqtaawdcykp7xqpk03t0w2dam92jyzqa945cpmk3t46s7z5xmd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvNGZlbW9WUTFyd0t5S0Nh
            TWVDWVJqY0d1MXpiSWU3eEh2bklJL3F1RWdBCis4aVNtdkg1cjYrVllydjNTN3k3
            T3Foa2MwbDVld1pqdWVPU1M2aUZQd1UKLS0tIDlpTGhzTVBFc1pyTUFGMkNIRXhG
            ZTBuZmdKQ2NJTGllVytncUpZc3hObnMKzLYOZ8QxCsi2sromlG5oyMaveH+9YCp2
            HDBleaEA5sMLEIih7aYcQcF8xfVnCAhrf0s7OCLj7L6fDl4zWjq7mA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-13T04:57:39Z"
    mac: ENC[AES256_GCM,data:k9yJia91HhbOsYQBvbisI2yaYZioi36vc91VQYYF+I+GbbojvGvVacYmMaoAj6UFjp42PAiym+zjhLEs4aG2EjFTIHiisR8X2apsx37cu5o8T1SeVX1YCq7QIZsBy0H3Y0XC0/zyP1Y4MBhZCmmcmpjrI6+Vx959VAxjVoWw0L4=,iv:0JO5b/TRQJ2lab0fi6pdGJgdd+jnJTbypkXs3WzAWYk=,tag:xTc/fDT7ZKtSi1kSlivo/g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
