apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: harbor
      version: "1.18.2"
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: harbor
      interval: 12h
  install:
    timeout: 60m
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  values:
    expose:
      type: clusterIP
      tls:
        enabled: false

    externalURL: https://harbor.home.com

    existingSecretAdminPassword: harbor-admin-secret
    existingSecretAdminPasswordKey: password

    database:
      type: external
      external:
        host: "postgres-cluster-rw.cnpg-pods.svc.cluster.local"
        port: "5432"
        username: "harbor"
        coreDatabase: "harbor"
        existingSecret: harbor-db-credentials
        existingSecretKey: password

    redis:
      type: external
      external:
        addr: "redis-cluster-ip.redis.svc.cluster.local:6379"
        sentinelMasterSet: ""

    persistence:
      enabled: true
      resourcePolicy: "keep"
      imageChartStorage:
        disableredirect: true
        type: s3
        s3:
          bucket: harbor
          region: us-east-1
          regionendpoint: "http://minio-backend-loadbalancer.minio.svc.cluster.local:9000"
          secure: false
          existingSecret: harbor-minio-credentials

      persistentVolumeClaim:
        jobservice:
          jobLog:
            storageClass: longhorn-slow-single-replica
            accessMode: ReadWriteOnce
            size: 1Gi
        trivy:
          storageClass: longhorn-slow-single-replica
          accessMode: ReadWriteOnce
          size: 5Gi

    trivy:
      enabled: true

    notary:
      enabled: false

    nginx:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: role/store
                    operator: In
                    values:
                      - "true"
    portal:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: role/store
                    operator: In
                    values:
                      - "true"
    core:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: role/store
                    operator: In
                    values:
                      - "true"
    jobservice:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: role/store
                    operator: In
                    values:
                      - "true"
    registry:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: role/store
                    operator: In
                    values:
                      - "true"
    exporter:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: role/store
                    operator: In
                    values:
                      - "true"