apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- helmrepository.yaml
- helmrelease.yaml
- harbor-admin-secret.yaml
- harbor-db-credentials-secret.yaml
- harbor-minio-credentials-secret.yaml
- harbor-db-init-job.yaml
- httproute.yaml
- httpsroute.yaml
- dockerhub-credentials-secret.yaml
- create-minio-harbor-bucket.yaml
- harbor-db-init-job-serviceaccount.yaml
- harbor-tls-cert.yaml
- proxy-projects-job.yaml