apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  interval: 30m
  timeout: 10m
  
  install:
    remediation:
      retries: 3
  
  upgrade:
    remediation:
      retries: 3
  
  chart:
    spec:
      chart: metrics-server
      version: '3.x'
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: monitoring
      interval: 12h
  
  values:
    args:
      - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
      - --kubelet-use-node-status-port
      - --metric-resolution=15s
      - --kubelet-insecure-tls  # Skip TLS verification for kubelet
    
    apiService:
      create: true
      insecureSkipTLSVerify: true  # Skip TLS verification for API service
    
    resources:
      requests:
        cpu: "100m"
        memory: "200Mi"
      limits:
        cpu: "200m"
        memory: "400Mi"
    
    replicas: 1