{{- if .Values.sampleApp.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.sampleApp.app | default "sample-app" }}
  namespace: {{ .Values.sampleApp.namespace | default "sample-app-namespace" }}
spec:
  replicas: {{ .Values.sampleApp.replicas | default 3 }}
  selector:
    matchLabels:
      app: {{ .Values.sampleApp.app | default "sample-app" }}
  template:
    metadata:
      labels:
        app: {{ .Values.sampleApp.app | default "sample-app" }}
    spec:
      containers:
      - name: {{ .Values.sampleApp.app | default "sample-app" }}
        image: {{ .Values.sampleApp.image.repository | default "nginx" }}:{{ .Values.sampleApp.image.tag | default "latest" }}
        command:
        - /bin/sh
        - -c
        - "echo $(hostname) > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"
        ports:
        - containerPort: 80
{{- end }}