{{- if .Values.sampleApp.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.sampleApp.app | default "sample-app" }}-loadbalancer
  namespace: {{ .Values.sampleApp.namespace | default "sample-app-namespace" }}
spec:
  selector:
    app: {{ .Values.sampleApp.app | default "sample-app" }}
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  # type: LoadBalancer
  type: ClusterIP # With Nginx Ingress Controller, we use ClusterIP
{{- end }}